Repository DURYMONG/DURYMONG-Android, pull requests merged in 2025-02, with the labels that each got.

#29 [FEAT] 5-2 일지화면 viewmodel 생성, Retrofit 사용환경 구성
  app/build.gradle.kts
  app/src/main/java/com/example/durymong/model/dto/request/chat/DummyChatRequest.kt
  app/src/main/java/com/example/durymong/model/dto/request/column/DummyColumnRequest.kt
  app/src/main/java/com/example/durymong/model/dto/request/doit/DummyDoItRequest.kt
  app/src/main/java/com/example/durymong/model/dto/request/mong/DummyMongRequest.kt
  app/src/main/java/com/example/durymong/model/dto/request/user/DummyUserRequest.kt
  app/src/main/java/com/example/durymong/model/dto/response/chat/DummyChatResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/column/ColumnResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/doit/DummyDoItResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/mong/DummyMongResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/user/DummyUserResponse.kt
  app/src/main/java/com/example/durymong/model/repository/ChatRepository.kt
  app/src/main/java/com/example/durymong/model/repository/ColumnRepository.kt
  app/src/main/java/com/example/durymong/model/repository/DoItRepository.kt
  app/src/main/java/com/example/durymong/model/repository/MongRepository.kt
  app/src/main/java/com/example/durymong/model/repository/UserRepository.kt
  app/src/main/java/com/example/durymong/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/durymong/retrofit/service/ChatService.kt
  app/src/main/java/com/example/durymong/retrofit/service/ColumnService.kt
  app/src/main/java/com/example/durymong/retrofit/service/DoItService.kt
  app/src/main/java/com/example/durymong/retrofit/service/MongService.kt
  app/src/main/java/com/example/durymong/retrofit/service/UserService.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DailyRecordFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/MonthlyRecordFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/adapter/RVAdapterMonthlyRecord.kt
  app/src/main/java/com/example/durymong/view/do_it/record/viewmodel/MonthlyRecordViewModel.kt
  app/src/main/res/layout/fragment_do_it_daily_record.xml
  app/src/main/res/layout/fragment_do_it_monthly_record.xml
  gradle/libs.versions.toml
Labels: feat

#36 [FEAT] Dto 수정, service, repository 예시 코드 작성
  app/src/main/java/com/example/durymong/model/AuthInterceptor.kt
  app/src/main/java/com/example/durymong/model/TokenManager.kt
  app/src/main/java/com/example/durymong/model/dto/response/column/CategoryResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/column/CategoryResponseDto.kt
  app/src/main/java/com/example/durymong/model/repository/ColumnRepository.kt
  app/src/main/java/com/example/durymong/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/durymong/retrofit/service/ColumnService.kt
  app/src/main/java/com/example/durymong/view/column/viewmodel/ColumnViewModel.kt
Labels: feat

#41 [fix]: 토큰 저장오류 수정
  app/src/main/java/com/example/durymong/model/repository/UserRepository.kt
  app/src/main/java/com/example/durymong/view/column/ColumnFragment.kt
  app/src/main/java/com/example/durymong/view/user/AuthActivity.kt
  app/src/main/java/com/example/durymong/view/user/viewmodel/AuthViewModel.kt
Labels: fix, Merge Ok

#42 [ui] ai chat bot 화면구성
  app/src/main/res/drawable/ic_chat_book.xml
  app/src/main/res/drawable/ic_chat_chart.xml
  app/src/main/res/drawable/ic_chat_star.xml
  app/src/main/res/drawable/img_chat_bot_bear.png
  app/src/main/res/drawable/img_chat_bot_cat.png
  app/src/main/res/drawable/img_chat_bot_decorate.png
  app/src/main/res/drawable/img_chat_bot_dog.png
  app/src/main/res/drawable/img_chat_from_ai.9.png
  app/src/main/res/drawable/v_chat_oval_stroke_2dp.xml
  app/src/main/res/drawable/v_chat_oval_stroke_4dp.xml
  app/src/main/res/drawable/v_chat_radius_8dp_stroke_gray3_solid_white.xml
  app/src/main/res/drawable/v_chat_radius_8dp_stroke_purple_solid_white.xml
  app/src/main/res/drawable/v_chat_radius_about3.xml
  app/src/main/res/drawable/v_chat_raduis_15dp.xml
  app/src/main/res/layout/fragment_chat_detail.xml
  app/src/main/res/layout/fragment_chat_main.xml
  app/src/main/res/layout/item_chat_activity.xml
  app/src/main/res/layout/item_chat_test.xml
  app/src/main/res/values/strings.xml
Labels: ui

#45 [FEAT] 칼럼 메뉴 기능 구현 완료
  .DS_Store
  app/.DS_Store
  app/src/.DS_Store
  app/src/main/.DS_Store
  app/src/main/java/.DS_Store
  app/src/main/java/com/.DS_Store
  app/src/main/java/com/example/.DS_Store
  app/src/main/java/com/example/durymong/.DS_Store
  app/src/main/java/com/example/durymong/model/.DS_Store
  app/src/main/java/com/example/durymong/model/AuthInterceptor.kt
  app/src/main/java/com/example/durymong/model/TokenManager.kt
  app/src/main/java/com/example/durymong/model/dto/.DS_Store
  app/src/main/java/com/example/durymong/model/dto/response/.DS_Store
  app/src/main/java/com/example/durymong/model/dto/response/column/CategoryResponseDto.kt
  app/src/main/java/com/example/durymong/model/dto/response/column/ColumnResponseDto.kt
  app/src/main/java/com/example/durymong/model/dto/response/column/KeywordSearchResponseDto.kt
  app/src/main/java/com/example/durymong/model/repository/ColumnRepository.kt
  app/src/main/java/com/example/durymong/retrofit/.DS_Store
  app/src/main/java/com/example/durymong/retrofit/service/ColumnService.kt
  app/src/main/java/com/example/durymong/view/.DS_Store
  app/src/main/java/com/example/durymong/view/column/.DS_Store
  app/src/main/java/com/example/durymong/view/column/ColumnDetailFragment.kt
  app/src/main/java/com/example/durymong/view/column/ColumnFragment.kt
  app/src/main/java/com/example/durymong/view/column/adapter/RVAdapterColumnCategory.kt
  app/src/main/java/com/example/durymong/view/column/adapter/RVAdapterColumnSearchResult.kt
  app/src/main/java/com/example/durymong/view/column/viewmodel/ColumnViewModel.kt
  app/src/main/java/com/example/durymong/view/user/AuthActivity.kt
  app/src/main/res/.DS_Store
  app/src/main/res/layout/fragment_column.xml
  app/src/main/res/layout/fragment_column_detail.xml
  app/src/main/res/layout/item_column_category.xml
  app/src/main/res/layout/item_column_search_result.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, ui, Merge Ok

#51 [Refactor] access token 만료시 재발급 로직 구현
  app/src/main/java/com/example/.DS_Store
  app/src/main/java/com/example/durymong/model/AuthInterceptor.kt
  app/src/main/java/com/example/durymong/model/dto/request/user/ReIssueTokenRequest.kt
  app/src/main/java/com/example/durymong/model/dto/response/user/ReIssueTokenResponse.kt
  app/src/main/java/com/example/durymong/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/durymong/retrofit/service/UserService.kt
  app/src/main/java/com/example/durymong/view/column/ColumnDetailFragment.kt
  app/src/main/java/com/example/durymong/view/column/adapter/RVAdapterColumnCategory.kt
  app/src/main/java/com/example/durymong/view/do_it/viewmodel/DoItViewModel.kt
  app/src/main/java/com/example/durymong/view/user/AuthActivity.kt
  app/src/main/java/com/example/durymong/view/user/viewmodel/AuthViewModel.kt
  app/src/main/res/layout/item_column_category.xml
  app/src/main/res/layout/item_column_category_description.xml
Labels: feat, Merge Ok

#54 [FEAT] 5-5, 5-6, 5-7 기능 구현 / 토큰 만료시 로그아웃 처리
  .DS_Store
  app/.DS_Store
  app/src/.DS_Store
  app/src/main/.DS_Store
  app/src/main/java/.DS_Store
  app/src/main/java/com/.DS_Store
  app/src/main/java/com/example/.DS_Store
  app/src/main/java/com/example/durymong/.DS_Store
  app/src/main/java/com/example/durymong/MainActivity.kt
  app/src/main/java/com/example/durymong/model/.DS_Store
  app/src/main/java/com/example/durymong/model/TokenManager.kt
  app/src/main/java/com/example/durymong/model/dto/.DS_Store
  app/src/main/java/com/example/durymong/model/dto/response/.DS_Store
  app/src/main/java/com/example/durymong/model/dto/response/doit/UserDailyBotChatChoiceResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/doit/UserDailyBotChatResponse.kt
  app/src/main/java/com/example/durymong/model/dto/response/doit/UserDailyChatResponse.kt
  app/src/main/java/com/example/durymong/model/repository/DoItRepository.kt
  app/src/main/java/com/example/durymong/retrofit/.DS_Store
  app/src/main/java/com/example/durymong/retrofit/service/DoItService.kt
  app/src/main/java/com/example/durymong/view/.DS_Store
  app/src/main/java/com/example/durymong/view/column/.DS_Store
  app/src/main/java/com/example/durymong/view/do_it/.DS_Store
  app/src/main/java/com/example/durymong/view/do_it/record/.DS_Store
  app/src/main/java/com/example/durymong/view/do_it/record/DailyDiaryDisabledFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DailyDiaryFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DailyRecordFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DoItChatHistoryCharacterFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DoItChatHistoryFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/DoItMongHistoryFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/MonthlyRecordFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/record/adapter/RVAdapterChatbotHistory.kt
  app/src/main/java/com/example/durymong/view/do_it/record/adapter/RVAdapterSymptoms.kt
  app/src/main/java/com/example/durymong/view/do_it/record/adapter/RVAdapterTestRecommendation.kt
  app/src/main/java/com/example/durymong/view/do_it/test_page/TestPageFragment.kt
  app/src/main/java/com/example/durymong/view/do_it/viewmodel/DoItViewModel.kt
  app/src/main/java/com/example/durymong/view/user/AuthActivity.kt
  app/src/main/res/.DS_Store
  app/src/main/res/drawable/ic_chat_bubble_chatbot_history.xml
  app/src/main/res/drawable/ic_chat_bubble_mong.xml
  app/src/main/res/drawable/ic_chat_bubble_user.xml
  app/src/main/res/drawable/ic_chatbot_card_arrow.xml
  app/src/main/res/drawable/ic_mont_test_select_button.xml
  app/src/main/res/layout/fragment_do_it_chat_history.xml
  app/src/main/res/layout/fragment_do_it_chat_history_character.xml
  app/src/main/res/layout/fragment_do_it_daily_diary.xml
  app/src/main/res/layout/fragment_do_it_daily_diary_disabled.xml
  app/src/main/res/layout/fragment_do_it_daily_record.xml
  app/src/main/res/layout/fragment_do_it_mong_history.xml
  app/src/main/res/layout/fragment_test_page.xml
  app/src/main/res/layout/item_chatbot_test_category.xml
  app/src/main/res/layout/item_do_it_chatbot_card.xml
  app/src/main/res/layout/item_doit_chatbot_symptom.xml
  app/src/main/res/layout/item_test_five.xml
  app/src/main/res/layout/item_test_four.xml
  app/src/main/res/layout/item_test_three.xml
Labels: feat, Merge Ok

#55 [fix]: 하단 내비게이션 바 아이콘 투명도 수정
  app/src/main/res/drawable/ic_nav_column_selected.xml
  app/src/main/res/drawable/ic_nav_do_it_selected.xml
Labels: fix
